name: nst-data
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - demquery
  - fastkml
  - fiona
  - gdal
  - geojson
  - geopandas
  - gpxpy
  - jupyter
  - lxml
  - mercantile
  - mkdocs
  - mkdocs-material
  - networkx
  - numpy
  - osmnx
  - pandas
  - pint
  - pip
  - pygments
  - pyproj
  - pyshp
  - python-chromedriver-binary
  - python-dateutil
  - python-dotenv
  - python>=3.6
  - pytz
  - rasterio
  - requests
  - scipy
  - selenium
  - shapely
  - supermercado
  - wikipedia
  - xlrd
  - pip:
    - keplergl_quickvis
    - opencage
    - osxphotos
    - python-language-server[all]
