name: create-database
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - fiona
  - gdal # needed?
  - geojson
  - geopandas
  - gpxpy
  - jupyter
  - lxml
  - numpy
  - pandas
  - pint
  - pip
  - pyproj
  - python-dotenv
  - python=3
  - rasterio
  - requests
  - scipy
  - shapely
  - xlrd
  - pip:
    - python-language-server[all]
